# Generated by Django 4.1.7 on 2023-03-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options_alter_order_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="arhived",
            new_name="archived",
        ),
    ]
